- name: Play Level Variables
  hosts: localhost
  vars:
    URL: play.variable.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
       msg: URL = {{URL}}

- name: Play Level Variables from Files
  hosts: localhost
  vars_files:
    -var.yml
  tasks:
    - name: Print Play Variable from file
      ansible.builtin.debug:
        msg: URL = {{URL}}