- name: Play Level Variables
  hosts: localhost
  vars:
    URL: play.variable.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
       msg: URL = {{URL}}

- name: Play Level Variables from Files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variable from file
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Task Level Variables
  hosts: localhost
  tasks:
    - name: Print Play Variable from file
      vars :
        URL : Task.variable.com
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Vars from Inventory
  hosts: all
  tasks:
    - name: Print Variable from Inventory
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Register a Variable
  hosts: localhost
  tasks:
    - name: Get Uptime Output
      ansible.builtin.shell: uptime
      register: out

    - name: Print Out
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Declare a Variable
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"

    - name: Print Variable Status
      ansible.builtin.debug:
        msg: "{{ status }}"